name: Run tests

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild test -project IRHexColorDemo/IRHexColorDemo.xcodeproj -scheme IRHexColorDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'name=iPhone 11'
